version: '3.8'

services:
    db:
      image: pgvector/pgvector:pg16
      restart: always
      volumes:
        - pgdata:/var/lib/postgresql/data

        # the below way will auto run the sql files in the directory when the container starts
        # - ./init-scripts:/docker-entrypoint-initdb.d  # Mount local directory with .sql/.csv files

        # go with manual way to run the sql files
        - ./sql-init-scripts:/init-scripts  # Mount local directory with .sql/.csv files

      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: example

volumes:
  pgdata:
